apiVersion: v1
kind: Service
metadata:
  name: maria-service
  namespace: maria-namespace
spec:
  selector:
    app: maria-student
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8093
  type: NodePort
