apiVersion: v1
kind: Secret
metadata:
  name: maria-secret
  namespace: maria-namespace
type: Opaque
stringData:
  SERVER_PORT: "8093"
  SPRING_R2DBC_URL: "r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
