apiVersion: v1
kind: Secret
metadata:
  name: maria-12-secret
  namespace: maria-12-namespace
type: Opaque
stringData:
  SERVER_PORT: "9090"
  SPRING_R2DBC_URL: "r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
