apiVersion: v1
kind: Service
metadata:
  name: maria-12-service
  namespace: maria-12-namespace
spec:
  selector:
    app: maria-student
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  type: NodePort
